Issue 781
FeatureIDE/FeatureIDE pull request #1124
Opened 2021-06-08 12:33 UTC by johannesherschel

The constraint dialog now provides proposals for features with spaces and features equal to operator names when typing a quotation mark. Proposals are now also dependent on previous text, i.e. operators are proposed after a feature and vice versa.

2021-06-14 07:36 UTC, tthuem commented
> Proposals are now also dependent on previous text, i.e. operators are proposed after a feature and vice versa.

We have had this functionality already implemented before. The content assist has recognized what is expected next. Why is there a new implemented of it?

2021-06-14 12:09 UTC, Rahel12342 commented
It was not already implemented. Theoretically yes, practically there was a method supposed to do so (getProposalList()) which had a lot of TODOs and just returned a list with all proposals instead of filtered ones. See the changes we made in getProposalList() in ConstraintContentProposalProvider.

2021-06-14 12:14 UTC, SundermannC requested changes
Looks good, only one detail should be changed

2021-06-14 12:14 UTC, SundermannC commented on plugins/de.ovgu.featureide.fm.ui/src/de/ovgu/featureide/fm/ui/editors/ConstraintContentProposalProvider.java
> +				proposals.add(new ContentProposal("and"));
Inconsistent usage of constants. Please also use constant strings for "and" and "or"

2021-06-14 12:14 UTC, SundermannC commented on plugins/de.ovgu.featureide.fm.ui/src/de/ovgu/featureide/fm/ui/editors/ConstraintContentProposalProvider.java
> +	 * @author Johannes Herschel
Only one author. intended?

2021-06-16 07:17 UTC, tthuem commented
Please have a look at older versions. This has been implemented before. I would start at a three year old version, download and test it. Then go to newer or older versions depending on whether it works or not. Then, take a look at the code and inspect why it was removed.

2021-06-16 13:34 UTC, johannesherschel commented
The functionality apparently was removed with de9b9e0 which noted that it was buggy, and 633664b added TODO notes on the desired behaviour. The old implementation indeed looks buggy to me.

2021-06-16 20:47 UTC, tthuem commented
Thanks for double checking. @pinnecke did a heavy refactoring back then and apparently after six years we are still struggling to get everything working as it was before.

2021-06-21 06:10 UTC, SundermannC approved these changes

2021-06-21 06:10 UTC, merged