Issue 1076 4
FeatureIDE/FeatureIDE pull request #1146
Opened 2021-07-22 09:27 UTC by Rahel12342

Fixes task 4 from issue #1076.
Changed the isValidSelection method for actions that are included in the context menu. Now it returns false when the action is not allowed for the selected feature.

2021-07-23 09:57 UTC, SundermannC requested changes
Looks good overall. There are two seemingly equivalent methods. There should be only a single method that is accessible for both classes.

2021-07-23 09:57 UTC, SundermannC commented on plugins/de.ovgu.featureide.fm.ui/src/de/ovgu/featureide/fm/ui/editors/featuremodel/actions/DeleteAction.java
> +	private boolean hasExternalFeature(IStructuredSelection selection) {
Seems equivalent to the method in MultipleSelectionAction. It would be better to use the same method in this case.

2021-07-23 15:22 UTC, SundermannC approved these changes

2021-07-23 15:22 UTC, merged

2021-08-17 13:39 UTC, h3ssto commented on plugins/de.ovgu.featureide.fm.ui/src/de/ovgu/featureide/fm/ui/editors/featuremodel/actions/AFeatureModelAction.java
> +		for (final Object selectedElement : selection) {
This crashes the CI as it does not compile / work under Java 8. Please fix asap! @Rahel12342