Fixes #1459: UVL Reader now uses parent folder even with trivial relative path
FeatureIDE/FeatureIDE pull request #1471
Opened 2024-02-08 11:40 UTC by SundermannC

2024-02-13 15:59 UTC, skrieter requested changes

2024-02-13 15:59 UTC, skrieter commented on plugins/de.ovgu.featureide.fm.core/src/de/ovgu/featureide/fm/core/io/uvl/UVLFeatureModelFormat.java
> +			rootModel = uvlModelFactory.parse(source.toString(), getParentDirectoryName(path));
`rootModel = uvlModelFactory.parse(source.toString(), path.resolve("..").normalize().toString()); `

2024-02-13 15:59 UTC, skrieter commented on plugins/de.ovgu.featureide.fm.core/src/de/ovgu/featureide/fm/core/io/uvl/UVLFeatureModelFormat.java
> +
remove

2024-02-13 15:59 UTC, skrieter commented on plugins/de.ovgu.featureide.fm.core/src/de/ovgu/featureide/fm/core/io/uvl/UVLFeatureModelFormat.java
> +import java.nio.file.Paths;
remove

2024-03-05 16:47 UTC, SundermannC commented
Embedded feedback, refactoring seems to behave as expected.

2024-03-05 16:48 UTC, merged